### ISSUE TITLE
Lighting Errors

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#16]
After performing larger edits, lighting errors tend to occur
![2019-01-16_10 21 56](https://user-images.githubusercontent.com/22693741/51262766-9d757000-1978-11e9-9242-5b392bd54134.png)

This is am image of the bugged lighting

No console errors.

Using the Vector update IronApollo sent out

CraftBukkit version git-Spigot-f56e2e7-0c715b3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT

I can manually place blocks to update the lighting.

**Comment by RealmportalMC** [comment]
@IronApollo

**Comment by dextonanderson** [comment]
Just confirming this is still an issue. Was able to reproduce it by setting a large area to stone. Using new-vector-system branch

**Comment by AeSix** [comment]
https://puu.sh/D30wa/e67b561a0e.png
Also confirmed.  Though it did try to relight the area, it quit before it was done.

Applicable portion of the config (this is defaults)
```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 1
  # If existing lighting should be removed before relighting
  remove-first: false
```
