### ISSUE TITLE
required a schematic-path by FAWE (based on the installation without worldedit)

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/FastAsyncWorldEdit-1.13#167]
#Bug-Report for 1.13.x

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
1.13.128

**[REQUIRED] Spigot/Paper Version Number:** 
PaperSpigot 1.13.2

**[REQUIRED] Description of the problem:**
In the last time (1.12.x) FAWE and FAVS used the path-config option of WorldEdit like

```
[...]

saving:
    dir: '/home/redstoneworld/minecraft-server/server1/schematics'

[...]
```

But at now FAVS down't work with installed WorldEdit (as it says in the installation description) and now FAWE need a own schematic-path-option.

Currently it's not a part of the FAWE confg:

```
# Paths for various directories
paths:
  tokens: "tokens"
  # Put any minecraft or mod jars for FAWE to be aware of block textures
  textures: "textures"
  heightmap: "heightmap"
  history: "history"
  # Multiple servers can use the same clipboards
  #  - Use a shared directory or NFS/Samba
  clipboard: "clipboard"
  # Each player has their own sub directory for schematics
  per-player-schematics: true
  commands: "commands"
```

I have more than one server with a central schematic-source and need based the configuration and installation change a path-config option in FAWE. Can you add this, please?

**Plugins being used on the server:**
I use FAWE + FAVS

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin
