### ISSUE TITLE
Lighting in pastes and relighting tasks is broken.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#50]
Paper dev 525 (Spigot 1.13.2)
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2

Pasted in a build schematic, everything had a light level of 0.

![link](https://i.imgur.com/u9oxvvQ.jpg)

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 1
  # If existing lighting should be removed before relighting
  remove-first: false
```

Tried ```//desel```, ```//removelighting``` and ```//fixlighting```, but didn't relight anything.

Also tried these settings to no avail. 
```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: false
  async: false
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 2
  # If existing lighting should be removed before relighting
  remove-first: true
```

**Comment by Combustible** [comment]
Highly recommend LightCleaner as a replacement for FAWE's forever-broken relighting system. I've messed with it *a lot* and never got it to work all the way right, even in 1.12. 

https://www.spigotmc.org/resources/light-cleaner.42469/

**Comment by AeSix** [comment]
duplicate / similar to https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/26

This is still an issue (at least to some extent) with FAWE-NVS 165.

**Comment by mibby** [comment]
Lighting is still broken with all worldedit operations and pastes as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e (3/25 compile).

Tested with ``/fill dirt 10``.
![link3](https://i.imgur.com/M2ujAIE.png)

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: false
  async: false
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 2
  # If existing lighting should be removed before relighting
  remove-first: true
```

Also tested with ``remove-first: false`` which unfortunately had no effect.
